server:
  port: 8080
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:4200"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: card-service
          uri: http://localhost:8082
          predicates:
            - Path=/cards/**
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/inventories/**
        - id: room-service
          uri: http://localhost:8084
          predicates:
            - Path=/rooms/**
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
      expiration: 600000000
      refresh-token:
        expiration: 604800000